# Usa la imagen de Node.js
FROM node:20.18.0

# Establece el directorio de trabajo
WORKDIR /app

# Copia el package.json y el package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el código de la aplicación
COPY . .

# Expone el puerto que utiliza NestJS
EXPOSE 3000

# Inicia el servidor en modo desarrollo
CMD ["npm", "run", "start:dev"]